### ISSUE TITLE
Use browserslist instead of compatibility flag

### ISSUE THREAD

**Issue by clarfonthey** [clean-css/clean-css#1002]
It would be a lot easier to configure this based upon the supported browsers instead of a specific flag.

**Comment by jakubpawlowicz** [comment]
That would be handy indeed - any ideas how to implement it?

**Comment by DylanYoung** [comment]
@jakubpawlowicz Check out https://github.com/postcss/autoprefixer/blob/9.6.1/lib/autoprefixer.js

**Comment by DylanYoung** [comment]
Note that postcss preset env is also using browserslist, but only passes it through to autoprefixer.

Since your compatibility seems to be all 'ie'-based, I suspect all you have to do is resolve the browserslist query, grab the lowest version of ie-supported and default to that version if no flag is specified (allow the CLI flag to override it of course).  You'll also probably want a config option to disable or override this behaviour.

**Comment by DylanYoung** [comment]
Also, curious: do you support modern CSS like postcss-preset-env or is this project mostly just a compressor?

**Comment by DylanYoung** [comment]
As a part of this work, you might want to look at using caniuse to automatically grab the support details for a given browser.  This was you could fully support all browsers resolved by the browserslist query.   After this is done, you can deprecate the `ie` flags and replace them with a generic `browserslist-override` argument.

**Comment by DylanYoung** [comment]
https://www.npmjs.com/package/caniuse-api

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
