### ISSUE TITLE
Modularize the codebase to allow reuse

### ISSUE THREAD

**Issue by jakubpawlowicz** [clean-css/clean-css#389]
See https://github.com/jakubpawlowicz/clean-css/issues/125#issuecomment-64838786 by @stevenvachon

**Comment by ben-eb** [comment]
@jakubpawlowicz You might like to have a look at my module https://github.com/ben-eb/colormin, for minimising color values. Because it normalises the value, it can convert between rgba/hsla/hex/keyword, always choosing the smallest possible value, with respect to alpha transparency.

I put it here because I don't think this should be a priority (separate issue) for you, but it definitely could yield some byte savings for clean-css should you want to modularise later on. :smiley:

**Comment by jakubpawlowicz** [comment]
@ben-eb Interesting! Thanks for the tip, I'll take a look when revisiting modularity.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
