### ISSUE TITLE
can't run when css has @import

### ISSUE THREAD

**Issue by da0ka** [clean-css/clean-css#958]
I tested v4.1.6(https://jakubpawlowicz.github.io/clean-css/). console reports `_.existsSync is not a function` when css has `@import "sample.css"` or `@import url("sample.css");`.
All options are default. Browser is Chrome 49.0.2623.112
for example
@import "sample.css";
a{color:#ff0000}

**Comment by jakubpawlowicz** [comment]
Currently imports cannot be resolved from within a browser. Any ideas how to make it work?

**Comment by omidakhavan** [comment]
+1

**Comment by optimalisatie** [comment]
The [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) could be used to rebase relative URLs so that you could use Fetch API for local files.

We have modified `lib/utils/is-remote-resource.js` to simply return `true`.

```javascript
function isRemoteResource(uri) {
    return true; // modified
    /* return REMOTE_RESOURCE_PATTERN.test(uri); */
}
```

The `fetch` option can then be used to import relative files. You would just need to know the base of the origin stylesheet or page URL.

```javascript
new CleanCSS({
    fetch: function(uri, inlineRequest, inlineTimeout, callback) {

        // rebase relative uri
        var base; // stylesheet href or page URL for inline <style>
        url = new URL(uri, base).href;

        // Fetch request
        // ...
    }
});
```

https://github.com/jakubpawlowicz/clean-css#fetch-option

**Comment by jakubpawlowicz** [comment]
Closing it now, please reopen if needed.
